export {default as Header} from './Header/Header'
export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Menu} from './Menu/Menu'
export {default as Services} from './Services/Services'
export {default as AddProduct} from './AddProduct/AddProduct'
export {default as Login} from './Authentication/Login'
export {default as Register} from './Authentication/Register'
